### ISSUE TITLE
:sparkles:feat: chat list, chat room 페이지 구현

### ISSUE THREAD

**Issue by suminara** [FRONTENDSCHOOL7/final-12-HoloNyamNyam#17]
## :sparkle: 구현할 기능
chat list, chat room 페이지 구현

## :memo: 상세 작업 내용
![135fgz](https://github.com/FRONTENDSCHOOL7/final-12-HoloNyamNyam/assets/138554423/7e8ee61a-7aa1-4958-b4e0-239e220580ec)
- [x] 채팅 리스트화면
- [x] 채팅룸 화면

## :construction: 구현 방법 및 예상 동작
- 하단 네비게이션 바에서 채팅 탭을 클릭하면 채팅리스트페이지로 이동합니다.
- 채팅방을 클릭하면 해당 유저와의 채팅방 페이지가 열립니다.

**Comment by redcontroller** [comment]
구현된 부분에서 이상한 동작을 확인했어요!
🐛 신규 메시지 표기된 채팅 목록의 오랜지색 동그라미에 마우스를 가져다 대면 다른 채팅 목록 아이템의 배경색이 변경됩니다

**Comment by redcontroller** [comment]
채팅 리스트 Mouse Hover하면 transition으로 색 변하는 건 정말 좋네요! 😀👍

**Comment by suminara** [comment]
> 구현된 부분에서 이상한 동작을 확인했어요! 🐛 신규 메시지 표기된 채팅 목록의 오랜지색 동그라미에 마우스를 가져다 대면 다른 채팅 목록 아이템의 배경색이 변경됩니다

감사해요! fix완료하였습니다!
