### ISSUE TITLE
✨feat: 버튼 컴포넌트 구현

### ISSUE THREAD

**Issue by Seunggyu008** [FRONTENDSCHOOL7/final-12-HoloNyamNyam#2]
## :sparkle: 구현할 기능

공통으로 쓰일 버튼 컴포넌트를 구현

## :memo: 상세 작업 내용

![image](https://github.com/FRONTENDSCHOOL7/final-12-HoloNyamNyam/assets/56462409/8978f294-d101-4499-ac8a-4cb4892fbed0)
- [x] 버튼 마크업 및 스타일링 구현
- [x] 활성화/비활성화 (active/inactive) 상태
- [x] 버튼의 사이즈 변경이 가능한 컴포넌트
- [  ] Welcome 페이지에 버튼에 로고 요소 추가

**Comment by redcontroller** [comment]
공통으로 사용되는 Button 컴포넌트 구현완료 했습니다.
코드리뷰에서 bgColor의 Styled-components Warning 해결 완료하고 이슈를 닫습니다! 😁

- 해결방법 : Warning이 발생하는 Props에서 대문자를 제거하고 참조 식별자($)를 붙여준다.
