### ISSUE TITLE
✨feat: 유저 회원가입 페이지 구현

### ISSUE THREAD

**Issue by Seunggyu008** [FRONTENDSCHOOL7/final-12-HoloNyamNyam#3]
## :sparkle: 구현할 기능
회원가입 페이지의 전체적인 UI 구현 및 기능 구현

## :memo: 상세 작업 내용

<p align = "center">
<img width="500" alt="image" src="https://github.com/FRONTENDSCHOOL7/final-12-HoloNyamNyam/assets/56462409/f0c857b9-464d-45e2-8241-2db6980d49c1">
</p>

회원가입
---
- [x] 이메일 및 비밀번호가 입력 되어있지 않다면 경고 메시지 띄우기
- [x] 입력된 이메일이 맞는 형식이 아닐 경우 경고 메시지 띄우기
- [x] 입력된 비밀번호가 필요한 조건을 충족 못 했을 경우 경고 메시지 띄우기 (6글자 이상, 특수문자 및 숫자 포함)
- [x] 입력된 이메일이 이미 존재하는지 비교 후 존재할 경우 경고 메시지 띄우기
- [x] "다음" 버튼을 누를 시 상세정보 입력 페이지로 이동

개인정보 입력
---
- [x] 전체적인 UI 구성
- [x] 계정 ID 유효성 검사
- [x] 사진 업로드 기능 구현
- [x] "확인" 버튼을 누를 시 계정 생성

### 회원가입 페이지
---
* 유저가 input을 누를시 focus가 됩니다.
* 이메일 및 비밀번호가 입력되어 있어야지만 "계속하기" 버튼이 활성화됩니다.
* 유저가 중복된 이메일을 입력 했을 경우 경고 메시지가 나타나고 이메일 input이 focus됩니다.
* 유효한 정보를 입력 후, "다음" 버튼을 누를 시 상세페이지 입력 페이지로 이동됩니다.
### 상세정보 페이지
---
* 유저가 input을 누를시 focus가 됩니다.
* 모든 input이 입력되어 있어야지만 "확인" 버튼이 활성화됩니다.
* 유저가 영문, 숫자, 밑줄 및 마침표 외에 문자를 계정ID input에 입력 했을 경우 경고 메시지가 나타나고 계정ID input이 focus됩니다.
* 유저가 중복된 계정ID를 입력 했을 경우 경고 메시지가 나타나고 계정ID input이 focus됩니다.
* 유효한 정보를 입력 후, "확인" 버튼을 누를 시 회원가입이 완료됩니다.

**Comment by gee0916** [comment]
승규님, SignUpForm.jsx 파일이 common 하위에 있던데 components 파일에 singup 하위 폴더를 만들어서 거기 넣는 게 맞아보입니다 .. ! 혹시 다른 이유가 있나요 ?
