### ISSUE TITLE
🐛💄Fix: 중간 피드백 사항

### ISSUE THREAD

**Issue by redcontroller** [FRONTENDSCHOOL7/final-12-HoloNyamNyam#76]
## :memo: 상세 작업 내용
- **Login**
    - [x] (JHJ) useRef로 로그인 화면 입장 시 이메일 input 박스 깜박임
- **Welcome**
  - [x] (JHJ) 웰컴페이지 로고 호버시 흰색
- **회원가입**
  - [x] (JSG) placeholder 텍스트 변경
  - [x] (JSG) 경고 메시지 수정 
  - [x] (JSG) 회원가입 스타일링 로그인과 균일하게 변경 
- **Navigation Bar**
  - [x] (JHJ) 네비바 ui,애니메이션 수정
- **냠냠평가 리스트**
    - [x] (JHJ) 타사용자, 사용자 모달 다르게 제공
       ~~(JHJ) 냠냠평가 모달 로딩 속도 개선~~ (보류)
    - [x] (JHJ) 냠냠평가 모달 디자인 변경 + 닫기 버튼 추가
    - [x] (JHJ) 타사용자, 사용자 냠냠평가 디테일 페이지 모달 다르게 제공
- **냠냠평가 등록**
  - [x] (OSM) 프로필 수정과 라벨, 인풋, 저장버튼 통일
  - [x] (OSM) 인풋 검색버튼 분리 css
  - [x] (OSM) 이미지 업로드 클릭 영역 전체 이미지, 포인트 버튼 크게
  - [x] (OSM) 헤더에 '냠냠평가 등록' 텍스트 추가
  - [x] (OSM) 수정 모달아닌 페이지 만들기
- **카카오맵**
   - [x] (JHJ) 헤더 더보기 버튼 삭제
   - [x] (JHJ) 맵 마커 변경
- **Profile**
  - [x] (KMG) Profile 페이지에서 FeedDetail 페이지로 이동 없이 하트(좋아요)를 올릴 수 있도록 변경
  - [x] (KMG) FeedDetail 페이지로 이동하는 클릭 이벤트 범위 축소
  - [x] (JHJ) 프로필 모달 설정 및 개인정보 -> 프로필 수정으로 이동
  - [x] (JHJ)  냠냠평가 오른쪽 패딩 주기
  - [x] (JHJ) 타사용자 헤더에 아이디 text 추가
  - [x] (JHJ) 프로필: 포스트 커서 포인터 변경
  - [x] (JHJ) 타사용자, 사용자 더보기 수정
  - [x] (JHJ) 스크롤 끝까지 내린 상태에서 네비 버튼 클릭시 데이터 사라짐 현상 
  - [x] (JHJ) 냠냠평가 최신순으로 유지
  - [x] (JHJ) 스크롤 끝까지 내린 상태에서 밑에 여백 확보 필요
- **프로필 수정**
  - [x] (JSG)계시물 수정이랑 스타일링 통합
  - [x] (JSG)localStorage에 정보 저장하여 프로필 수정 후 다시 로그인 반복 방지
  - [x] (JSG)이미지만 바꾸었을 경우 저장 버튼 활성화 되지 않는 이슈 해결
- **Chat List**
  - [x] (OSM) 채팅페이지 데이터,기능 개선
- **Home**
  - [x] (KMG) Feed 더보기 상세보기 모달의 라우팅 주소 수정
  - [x] (KMG) Feed 더보기 계정정보 이동시 프로필 정보 전달 이슈
  - [x] (JHJ) 콘텐츠 하단 커서 모양 바꾸기
  - [x] (JHJ) 하트와 댓글 아이콘 호버 애니메이션
  - [x] (JHJ) 댓글 svg 변경
- **FeedDetail**
  - [x] (KMG) 업로드한 이미지 비율에 관계없이 크기를 동일하게 유지
  - [x] (KMG) Feed 상세보기에서는 딤처리 없도록 수정
  - [x] (JHJ) 디테일 피드 헤더 수정
- **Error**
  - [x] (KMG) 아이콘 크기 축소
  - [x] (KMG) 아이콘과 텍스트, 버튼의 간격을 넓히기

**Comment by gee0916** [comment]
냠냠리스트 모달 닫기 버튼 없음

**Comment by suminara** [comment]
냠냠평가 양식 채우기 검사 에러

**Comment by suminara** [comment]
로딩페이지 범위 축소
